baseline:
  img_size: 224
  batch: 32
  ModelParams:
    weights: imagenet
    pooling: max
    epochs: 20
    initial_learning_rate: 0.001
img_size_50:
  img_size: 50
  batch: 32
  ModelParams:
    weights: imagenet
    pooling: max
    epochs: 20
    initial_learning_rate: 0.001
img_size_100:
  img_size: 100
  batch: 32
  ModelParams:
    weights: imagenet
    pooling: max
    epochs: 20
    initial_learning_rate: 0.001
img_size_300:
  img_size: 300
  batch: 32
  ModelParams:
    weights: imagenet
    pooling: max
    epochs: 20
    initial_learning_rate: 0.001
learning_rate_16:
  img_size: 224
  batch: 32
  ModelParams:
    weights: imagenet
    pooling: max
    epochs: 20
    initial_learning_rate: 0.000001
learning_rate_15:
  img_size: 224
  batch: 32
  ModelParams:
    weights: imagenet
    pooling: max
    epochs: 20
    initial_learning_rate: 0.00001
learning_rate_14:
  img_size: 224
  batch: 32
  ModelParams:
    weights: imagenet
    pooling: max
    epochs: 20
    initial_learning_rate: 0.0001
learning_rate_12:
  img_size: 224
  batch: 32
  ModelParams:
    weights: imagenet
    pooling: max
    epochs: 20
    initial_learning_rate: 0.01
learning_rate_11:
  img_size: 224
  batch: 32
  ModelParams:
    weights: imagenet
    pooling: max
    epochs: 20
    initial_learning_rate: 0.1
batch_16:
  img_size: 224
  batch: 16
  ModelParams:
    weights: imagenet
    pooling: max
    epochs: 20
    initial_learning_rate: 0.001
batch_8:
  img_size: 224
  batch: 8
  ModelParams:
    weights: imagenet
    pooling: max
    epochs: 20
    initial_learning_rate: 0.001
batch_64:
  img_size: 224
  batch: 64
  ModelParams:
    weights: imagenet
    pooling: max
    epochs: 20
    initial_learning_rate: 0.001